"""First-launch bootstrap: write a config template and offer to edit it.

Triggered from `cli.main()` when a data command runs without a config
file, and used as the body of `chronos init`. Both paths share the same
template + editor flow so there is exactly one canonical "first config"
experience.
"""

from __future__ import annotations

import contextlib
import os
import subprocess
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import TextIO

from chronos.config import ConfigError
from chronos.config import load as load_config

PromptFn = Callable[[str], str]
EditorFn = Callable[[Path], None]
IsInteractiveFn = Callable[[], bool]


# Comments survive only until the first `chronos account add ...` (which
# round-trips the parsed config and drops them), so they're written for
# the user's first read, not as a long-lived reference. The canonical
# example reference lives in `config-sample.toml` at the repo root.
TEMPLATE_TOML = b"""\
# chronos configuration
#
# Generated by `chronos init`. Path values support ~, $VAR, and %VAR%
# expansion. After editing, run `chronos sync` to fetch your calendars,
# or `chronos tui` to browse them.

config_version = 1
use_utf8 = false

# editor = "nvim"   # optional override of $EDITOR / $VISUAL


# ---------------------------------------------------------------------
# Example accounts. Uncomment one and replace placeholders, or use
# `chronos account add ...` from the command line instead.
# ---------------------------------------------------------------------

# # Basic auth: Nextcloud, Radicale, Apple Calendar, Baikal, ...
# [[accounts]]
# name = "personal"
# url = "https://caldav.example.com/dav/calendars/user/USER/"
# username = "USER@example.com"
# credential = { backend = "plaintext", password = "REPLACE-ME" }
# # mirror_path is optional; defaults to <user-data-dir>/mirror/<name>.
# # mirror_path = "~/.local/share/chronos/mirror/personal"
# # trash_retention_days defaults to 30.
# # include / exclude are Python regexes (re.fullmatch); default include = [".*"].

# # Google Calendar via OAuth 2.0. Only the client_id/client_secret from
# # your Google Cloud project are required; the CalDAV URL, username, and
# # OAuth scope are filled in by chronos. The OAuth client must be of
# # type "Desktop app" (the same type Thunderbird uses). The first
# # `chronos sync` will open your browser to the consent screen and
# # store the tokens automatically.
# [[accounts]]
# name = "google"
# [accounts.credential]
# backend = "google"
# client_id = "REPLACE-ME.apps.googleusercontent.com"
# client_secret = "REPLACE-ME"

# # Generic OAuth 2.0 (Microsoft / Outlook, custom IdPs): configure URL,
# # username, scope, and client credentials explicitly. The first sync
# # opens a browser using the loopback redirect flow (RFC 8252 + PKCE).
# [[accounts]]
# name = "outlook"
# url = "https://outlook.office365.com/"
# username = "you@outlook.com"
# [accounts.credential]
# backend = "oauth"
# client_id = "REPLACE-ME"
# client_secret = "REPLACE-ME"
# scope = "https://outlook.office.com/Calendars.ReadWrite"
"""


def write_template(config_path: Path) -> None:
    """Write `TEMPLATE_TOML` to `config_path` atomically (temp + rename)."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=".tmp-", suffix=".toml", dir=config_path.parent
    )
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(TEMPLATE_TOML)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, config_path)
    except BaseException:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp_name)
        raise


def offer_bootstrap(
    stdout: TextIO,
    stderr: TextIO,
    *,
    config_path: Path,
    prompt: PromptFn,
    open_editor: EditorFn,
) -> int:
    """Prompt the user to create a template and edit it.

    Used by `cli.main()` when a data command runs without a config. The
    user is asked twice: first to create the template, then to open it
    in their editor. Each prompt defaults to "yes" on bare Enter.

    Returns 0 if the bootstrap completed (config written, optionally
    edited and validated), 1 if the user declined or validation failed.
    Caller-injected `prompt` and `open_editor` keep this testable.
    """
    if config_path.exists():
        stderr.write(f"config already exists at {config_path}\n")
        return 1

    stdout.write(f"No chronos config at {config_path}.\n")
    if not _yes_default(prompt("Create a template now? [Y/n] ")):
        stdout.write("Skipped. Run `chronos init` later to create one.\n")
        return 1

    write_template(config_path)
    stdout.write(f"Wrote template to {config_path}\n")

    if _yes_default(prompt("Open it in your editor now? [Y/n] ")):
        try:
            open_editor(config_path)
        except subprocess.CalledProcessError as exc:
            stderr.write(f"editor exited non-zero: {exc}\n")
            stdout.write("You can edit the config later with `chronos config edit`.\n")
            return 0
        except FileNotFoundError as exc:
            stderr.write(f"editor not found: {exc}\n")
            stdout.write("Set $EDITOR or $VISUAL and run `chronos config edit`.\n")
            return 0
        try:
            load_config(config_path)
        except ConfigError as exc:
            stderr.write(f"config has errors: {exc}\n")
            stderr.write("Re-run `chronos config edit` to fix and re-validate.\n")
            return 1

    stdout.write(
        "\nNext steps:\n"
        "  chronos sync         # fetch calendars from configured accounts\n"
        "  chronos tui          # browse them\n"
    )
    return 0


def default_is_interactive() -> bool:
    """Both stdin and stdout must be a TTY for the prompt to be useful."""
    return sys.stdin.isatty() and sys.stdout.isatty()


def default_prompt(message: str) -> str:
    return input(message)


def _yes_default(response: str) -> bool:
    """Treat empty input as Yes; "y" / "yes" (any case) as Yes; else No."""
    return response.strip().lower() in ("", "y", "yes")


__all__ = [
    "TEMPLATE_TOML",
    "EditorFn",
    "IsInteractiveFn",
    "PromptFn",
    "default_is_interactive",
    "default_prompt",
    "offer_bootstrap",
    "write_template",
]
