#!/usr/bin/env bash
# Run a throwaway Dovecot IMAP server as an unprivileged user.
#
# Pony's sync engine is tested against a fake IMAP session, which is fast
# and finds defects in how message populations are shaped, but it cannot
# tell us how a real server assigns UIDs, bumps UIDVALIDITY, or answers
# APPEND.  This puts a real one on a high port under a scratch directory,
# with no root, no system packages and nothing outside $PREFIX.
#
#   scripts/dovecot_userspace.sh install    fetch + unpack the .debs
#   scripts/dovecot_userspace.sh start      start the server
#   scripts/dovecot_userspace.sh status     is it up?
#   scripts/dovecot_userspace.sh stop       stop it
#   scripts/dovecot_userspace.sh reset      wipe all mail, keep the install
#   scripts/dovecot_userspace.sh bump FOLDER
#                                           force a UIDVALIDITY change
#
# Then:  export PONY_IMAP_URL="imap://$USER:pony@127.0.0.1:PORT"
set -euo pipefail

PREFIX="${PONY_DOVECOT_PREFIX:-${HOME}/.cache/pony-dovecot}"
PORT="${PONY_DOVECOT_PORT:-14300}"
USERNAME="${USER:-$(id -un)}"
PASSWORD="pony"

ROOT="${PREFIX}/root"          # unpacked .debs
RUN="${PREFIX}/run"            # base_dir, pid, sockets
MAIL="${PREFIX}/mail"          # Maildir per user
CONF="${PREFIX}/dovecot.conf"
LOG="${PREFIX}/dovecot.log"
DEBS="${PREFIX}/debs"

# The dovecot binaries link against libdovecot.so under usr/lib/dovecot,
# which is not a default search path once the tree is relocated.
export LD_LIBRARY_PATH="${ROOT}/usr/lib/dovecot:${ROOT}/usr/lib/x86_64-linux-gnu:${ROOT}/usr/lib:${LD_LIBRARY_PATH:-}"
DOVECOT="${ROOT}/usr/sbin/dovecot"

# dovecot execs helpers such as /usr/bin/doveconf by absolute path, which
# an unpacked tree cannot satisfy.  bubblewrap gives us a user namespace
# in which the unpacked tree is layered *over* the real /usr — a plain
# bind would replace it and take the dynamic loader with it.  Writes go
# to a throwaway tmpfs, so nothing outside $PREFIX is touched and the
# view exists only for these processes.
in_sandbox() {
    bwrap --dev-bind / / \
          --overlay-src "${ROOT}/usr" --overlay-src /usr --tmp-overlay /usr \
          --setenv LD_LIBRARY_PATH "/usr/lib/dovecot" \
          "$@"
}

die() { echo "error: $*" >&2; exit 1; }

installed_ok() {
    [[ -x "${DOVECOT}" ]] && command -v bwrap >/dev/null &&
        in_sandbox /usr/sbin/dovecot --version >/dev/null 2>&1
}

install_dovecot() {
    # Idempotent and cheap: the harness calls this before every run, and
    # re-downloading and re-unpacking a working tree costs seconds each
    # time for nothing.  Pass --force to rebuild it anyway.
    if [[ "${1:-}" != "--force" ]] && installed_ok; then
        echo "Already installed under ${ROOT} ($(in_sandbox /usr/sbin/dovecot --version))"
        return 0
    fi
    mkdir -p "${DEBS}" "${ROOT}"
    echo "Resolving dependencies…"
    # The recursive closure, minus anything dpkg already has installed.
    local wanted=()
    while read -r pkg; do
        [[ -z "${pkg}" || "${pkg}" == *:* || "${pkg}" == "<"* ]] && continue
        if dpkg-query -W -f='${Status}' "${pkg}" 2>/dev/null \
             | grep -q "install ok installed"; then
            continue
        fi
        wanted+=("${pkg}")
    done < <(apt-cache depends --recurse --no-recommends --no-suggests \
                 --no-conflicts --no-breaks --no-replaces --no-enhances \
                 dovecot-imapd 2>/dev/null \
             | grep '^\w' | sort -u)

    echo "Downloading: ${wanted[*]:-<nothing missing>}"
    if ((${#wanted[@]})); then
        (cd "${DEBS}" && apt-get download "${wanted[@]}" >/dev/null)
    fi
    for deb in "${DEBS}"/*.deb; do
        [[ -e "${deb}" ]] || continue
        dpkg-deb -x "${deb}" "${ROOT}"
    done
    [[ -x "${DOVECOT}" ]] || die "dovecot binary missing under ${ROOT}"
    command -v bwrap >/dev/null || die "bubblewrap (bwrap) is required"
    echo "Installed under ${ROOT}"
    in_sandbox /usr/sbin/dovecot --version
}

# Write $2 to $1 only if it would change.  start() is called once per
# scenario, and rewriting identical bytes is churn for nothing.
write_if_changed() {
    local path="$1" content="$2"
    if [[ -f "${path}" ]] && [[ "$(cat "${path}")" == "${content}" ]]; then
        return 0
    fi
    printf '%s' "${content}" > "${path}"
}

write_config() {
    mkdir -p "${RUN}" "${MAIL}"
    # A password file rather than system accounts, so no privileged
    # lookup is needed.  The full passwd form carries the uid/gid/home
    # that the userdb needs; a bare user:password pair authenticates and
    # then fails with "missing userdb info".
    write_if_changed "${PREFIX}/passwd" "$(printf '%s:{PLAIN}%s:%s:%s::%s::\n' \
        "${USERNAME}" "${PASSWORD}" "$(id -u)" "$(id -g)" "${MAIL}/${USERNAME}")"
    write_if_changed "${CONF}" "$(cat <<EOF
# Generated by scripts/dovecot_userspace.sh — do not edit by hand.
# 2.4 requires both version declarations, and config_version first.
dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
base_dir = ${RUN}
state_dir = ${RUN}
log_path = ${LOG}
protocols = imap
listen = 127.0.0.1
ssl = no
auth_allow_cleartext = yes
auth_mechanisms = plain login

# Running unprivileged: no setuid, no chroot, and the mail process is
# this same user, so the usual uid floor has to allow it.
default_internal_user = ${USERNAME}
default_login_user = ${USERNAME}
# The packaged defaults reference a "dovecot" system group that a
# user-space unpack never creates.
default_internal_group = $(id -gn)
first_valid_uid = $(id -u)
last_valid_uid = $(id -u)

mail_driver = maildir
mail_path = ${MAIL}/%{user}
mail_home = ${MAIL}/%{user}

passdb passwd-file {
  passwd_file_path = ${PREFIX}/passwd
}
userdb passwd-file {
  passwd_file_path = ${PREFIX}/passwd
}

service imap-login {
  inet_listener imap {
    port = ${PORT}
  }
  chroot =
  user = ${USERNAME}
}
service auth {
  user = ${USERNAME}
}
EOF
)"
    echo "Config ready at ${CONF}"
}

port_open() { (exec 3<>"/dev/tcp/127.0.0.1/${PORT}") 2>/dev/null; }

start() {
    [[ -x "${DOVECOT}" ]] || die "not installed — run: $0 install"
    # Idempotent: a second start is a fatal error to dovecot itself, and
    # callers (the test harness especially) should not have to track it.
    if port_open; then
        echo "already listening on 127.0.0.1:${PORT}"
        return 0
    fi
    write_config
    # Detached from this shell's stdio: dovecot -F would otherwise hold
    # the terminal open for as long as it runs.
    in_sandbox /usr/sbin/dovecot -F -c "${CONF}" </dev/null >>"${LOG}" 2>&1 &
    local pid=$!
    echo "${pid}" > "${PREFIX}/dovecot.pid"
    sleep 2
    if ! kill -0 "${pid}" 2>/dev/null; then
        echo "--- ${LOG} ---" >&2
        tail -30 "${LOG}" 2>/dev/null >&2 || true
        die "dovecot exited immediately"
    fi
    echo "Listening on 127.0.0.1:${PORT} as ${USERNAME}/${PASSWORD}"
    echo "  export PONY_IMAP_URL=\"imap://${USERNAME}:${PASSWORD}@127.0.0.1:${PORT}\""
}

stop() {
    # Two pids matter: the bwrap wrapper we launched, and dovecot's own
    # master inside it.  Killing only the wrapper leaves master running
    # and holding the port, and its pid file then makes the next start
    # fail with "already running".
    local pidfile="${PREFIX}/dovecot.pid"
    [[ -f "${pidfile}" ]] && { kill "$(cat "${pidfile}")" 2>/dev/null || true; }
    [[ -f "${RUN}/master.pid" ]] && {
        kill "$(cat "${RUN}/master.pid")" 2>/dev/null || true
    }
    for _ in $(seq 40); do
        port_open || break
        sleep 0.2
    done
    rm -f "${pidfile}" "${RUN}/master.pid"
    port_open && die "port ${PORT} still in use"
    echo "stopped"
}

status() {
    python3 - "$PORT" <<'PY'
import socket, sys
port = int(sys.argv[1])
try:
    with socket.create_connection(("127.0.0.1", port), timeout=3) as s:
        print(s.recv(200).decode(errors="replace").strip())
except OSError as exc:
    print(f"not reachable on {port}: {exc}")
    raise SystemExit(1)
PY
}

reset_mail() {
    stop || true
    rm -rf "${MAIL}"
    mkdir -p "${MAIL}"
    echo "mail wiped"
}

# Force a UIDVALIDITY change the way a restore-from-backup does: drop the
# index and uid list for a mailbox, so the server assigns a new epoch.
bump_uidvalidity() {
    local folder="${1:-INBOX}"
    local dir="${MAIL}/${USERNAME}"
    [[ "${folder}" == "INBOX" ]] || dir="${dir}/.${folder}"
    [[ -d "${dir}" ]] || die "no such mailbox: ${dir}"
    stop >/dev/null || true
    find "${dir}" -maxdepth 1 \( -name 'dovecot-uidlist' -o -name 'dovecot.index*' \
        -o -name 'dovecot.list.index*' \) -delete
    echo "UIDVALIDITY reset for ${folder}; restart with: $0 start"
}

case "${1:-}" in
    install) install_dovecot "${2:-}" ;;
    start)   start ;;
    stop)    stop ;;
    status)  status ;;
    reset)   reset_mail ;;
    bump)    bump_uidvalidity "${2:-INBOX}" ;;
    *)       sed -n '2,20p' "$0" | sed 's/^# \?//' ; exit 1 ;;
esac
